"""Initial migration

Revision ID: 8fc62ecc4d1f
Revises: b5efe659e975
Create Date: 2024-07-05 13:14:33.798214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc62ecc4d1f'
down_revision = 'b5efe659e975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curriculo', schema=None) as batch_op:
        batch_op.alter_column('arquivo',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curriculo', schema=None) as batch_op:
        batch_op.alter_column('arquivo',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
